name: "Test workflow"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ARTIFACT_NAME: foo_bucket

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test
        run: |
          echo "test passed"

  aws_cli:
    runs-on: ubuntu-latest
    steps:
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.Z_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.Z_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: list buckets
        run: |
          echo "fake list of buckets" > buckets.txt
          mkdir foo
          echo "hello" > foo/world.txt

      - name: upload file
        uses: actions/upload-artifact@v2
        with:
          name: $ARTIFACT_NAME
          path: |
            foo
            buckets.txt

  print_job:
    runs-on: ubuntu-latest
    needs: aws_cli
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: $ARTIFACT_NAME

      - name: print buckets
        run: |
          cat buckets.txt
          echo "-----"
          cat foo/world.txt
          echo "-----"
          echo $ARTIFACT_NAME
