name: "Test workflow"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.Z_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.Z_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  ROLE_ARN: ${{ secrets.LAMBDA_ROLE_ARN }}
  ACCOUNT_ID: ${{ secrets.MINWO_ACCOUNT_ID }}

jobs:
  create_ecr_repo:
    runs-on: ubuntu-latest
    steps:
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          aws-region: us-east-1

      - name: create ecr repo
        run: aws ecr create-repository --repository-name book_recommender_2 --image-scanning-configuration scanOnPush=true --image-tag-mutability MUTABLE

  build_push:
    runs-on: ubuntu-latest
    needs: create_ecr_repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          aws-region: us-east-1

      - name: login - authenticate docker to push to ecr
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: build image
        run: docker build -t book_recommender_2:latest .

      - name: tag image
        run: docker tag book_recommender_2:latest ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/book_recommender_2:latest

      - name: push image
        run: docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/book_recommender_2:latest

  create_function:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          aws-region: us-east-1

      - name: create lambda function
        run: |
          aws lambda create-function \
          --function-name book_recommender_2 \
          --package-type Image \
          --role $ROLE_ARN \
          --code ImageUri=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/book_recommender_2:latest \
